### ISSUE TITLE
Question: What is ASCAppointment

### ISSUE THREAD

**Issue by israteneda** [Narias1999/visabot#1]
I was looking at the visa portal, but I did not find anything related to `ASCAppointment`.
Could you please tell me more about this variable?

**Comment by Narias1999** [comment]
Hi Israel! I guess it depends on the embassy of your country and the conditions that they require. In Colombia, most people need to get two appointments:
- The ASC is the first one when they get your biometric data and your passport.
- Then you have to go to the consulate appointment (Not required in some specific conditions). Here is where an embassy official does an the interview to determine if you are eligible for a Visa.

**Comment by israteneda** [comment]
oh got it, thanks for your answer @Narias1999
